openapi: 3.0.3
info:
  title: Performance Platform API
  version: 1.0.0
  description: API for managing tasks and evaluations for Qassim University Project
paths:
  /api/dashboard-summary/:
    get:
      operationId: dashboard_summary_retrieve
      tags:
      - dashboard-summary
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DashboardSummary'
          description: ''
  /api/evaluations/:
    get:
      operationId: evaluations_list
      tags:
      - evaluations
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Evaluation'
          description: ''
    post:
      operationId: evaluations_create
      tags:
      - evaluations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Evaluation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Evaluation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Evaluation'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
          description: ''
  /api/evaluations/{id}/:
    get:
      operationId: evaluations_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this evaluation.
        required: true
      tags:
      - evaluations
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
          description: ''
    put:
      operationId: evaluations_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this evaluation.
        required: true
      tags:
      - evaluations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Evaluation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Evaluation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Evaluation'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
          description: ''
    patch:
      operationId: evaluations_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this evaluation.
        required: true
      tags:
      - evaluations
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedEvaluation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedEvaluation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedEvaluation'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
          description: ''
    delete:
      operationId: evaluations_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this evaluation.
        required: true
      tags:
      - evaluations
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/my-evaluations/:
    get:
      operationId: my_evaluations_list
      tags:
      - my-evaluations
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Evaluation'
          description: ''
  /api/my-tasks/:
    get:
      operationId: my_tasks_list
      tags:
      - my-tasks
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
          description: ''
  /api/tasks/:
    get:
      operationId: tasks_list
      tags:
      - tasks
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
          description: ''
    post:
      operationId: tasks_create
      tags:
      - tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Task'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          description: ''
  /api/tasks/{id}/:
    get:
      operationId: tasks_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this task.
        required: true
      tags:
      - tasks
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          description: ''
    put:
      operationId: tasks_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this task.
        required: true
      tags:
      - tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Task'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          description: ''
    patch:
      operationId: tasks_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this task.
        required: true
      tags:
      - tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTask'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTask'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTask'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
          description: ''
    delete:
      operationId: tasks_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this task.
        required: true
      tags:
      - tasks
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/tasks/{task_id}/evaluation/:
    get:
      operationId: tasks_evaluation_retrieve
      parameters:
      - in: path
        name: task_id
        schema:
          type: integer
        required: true
      tags:
      - tasks
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
          description: ''
    post:
      operationId: tasks_evaluation_create
      parameters:
      - in: path
        name: task_id
        schema:
          type: integer
        required: true
      tags:
      - tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Evaluation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Evaluation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Evaluation'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Evaluation'
          description: ''
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    DashboardSummary:
      type: object
      properties:
        total_tasks:
          type: integer
        completed_tasks:
          type: integer
        evaluations:
          type: integer
      required:
      - completed_tasks
      - evaluations
      - total_tasks
    Evaluation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        objective_score:
          type: number
          format: double
          nullable: true
        subjective_score:
          type: number
          format: double
          nullable: true
        feedback:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        task:
          type: integer
        evaluator:
          type: integer
          nullable: true
      required:
      - created_at
      - id
      - task
    PatchedEvaluation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        objective_score:
          type: number
          format: double
          nullable: true
        subjective_score:
          type: number
          format: double
          nullable: true
        feedback:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        task:
          type: integer
        evaluator:
          type: integer
          nullable: true
    PatchedTask:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        deadline:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_at:
          type: string
          format: date-time
          readOnly: true
        assigned_to:
          type: integer
    StatusEnum:
      enum:
      - pending
      - in_progress
      - completed
      type: string
      description: |-
        * `pending` - Pending
        * `in_progress` - In Progress
        * `completed` - Completed
    Task:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        description:
          type: string
        deadline:
          type: string
          format: date-time
        status:
          $ref: '#/components/schemas/StatusEnum'
        created_at:
          type: string
          format: date-time
          readOnly: true
        assigned_to:
          type: integer
      required:
      - assigned_to
      - created_at
      - deadline
      - description
      - id
      - title
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
